kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: build
  image: node:10
  commands:
  - npm install
  - npm test
- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-rest-api
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [master, test]
    event: [push, tag]
