kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:12
  user: node
  commands:
  - npm install
  - npm test
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-rest-api
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [master, test]
event: [push, tag]
---
kind: secret
name: docker_username
data: U31NfaEMe08+2v9XKQoMSHsquDU5aYAWgre6sfLoD3vMGzGxPnEW+4JzZ6AErQFlkmA=
---
kind: secret
name: docker_password
data: 1YF3FpvcOsaWtP9s9gtuHuqhvUy0zdygDWeniRX92K2kVwnxJSezoKdBJE5MlX4dsvXFF3x/HqMX0EWn6G+ZvJsLmrPvzLKVGj9INfjn4N90dBhGA8DHz0XHySM=

